#local
server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/small2?setUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "@mnc2017317725"  #\u8FD9\u662F\u672C\u5730\u6570\u636E\u5E93\u5BC6\u7801

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl